version: '3'
services:
  app:
    container_name: connectviewer
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn run dev
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - .:/app
