FROM node:11.2.0-slim as builder

WORKDIR /app

COPY package.json yarn.lock* ./
RUN yarn config set workspaces-experimental true
RUN yarn install

COPY . .
RUN yarn run build

FROM nginx
EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html
